import { EventType, TravelEvent, Member, Booking } from './types';

// Animal Emojis for avatars
export const ANIMAL_AVATARS = ['🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐨', '🐯', '🦁', '🐮', '🐷', '🐸', '🐵', '🐔'];

// Members (Default)
export const DEFAULT_MEMBERS: Member[] = [
  { id: 'me', name: 'Unice', avatar: '🐰' },
  { id: 'lun', name: 'Lun', avatar: '🐱' },
];

export const TRIP_START_DATE = '2025-12-26';
export const TRIP_END_DATE = '2026-01-11';

// Seeded Schedule Data
export const SEEDED_EVENTS: TravelEvent[] = [
  // --- 12/26 ---
  {
    id: 'e1',
    date: '2025-12-26',
    time: '11:10',
    title: 'Flight UA872 TPE -> SFO',
    type: EventType.TRANSPORT,
    location: 'TPE Terminal 2',
    description: 'Flying time 11:30. Bring neck pillow.',
  },
  {
    id: 'e2',
    date: '2025-12-26',
    time: '08:30',
    title: 'Flight UA435 SFO -> EWR',
    type: EventType.TRANSPORT,
    location: 'SFO',
    description: 'Flying time 05:26.',
  },
  {
    id: 'e3',
    date: '2025-12-26',
    time: '18:00',
    title: 'Newark Airport Express',
    type: EventType.TRANSPORT,
    location: 'EWR',
    description: 'Bus to NY Port Authority.',
  },
  {
    id: 'e4',
    date: '2025-12-26',
    time: '21:00',
    title: 'Check-in Boston',
    type: EventType.STAY,
    location: 'Citizen M Boston Back Bay',
    description: '408 Newbury St. Rest day.',
  },
  // --- 12/27 ---
  {
    id: 'e5',
    date: '2025-12-27',
    time: '09:00',
    title: 'Harvard & MIT Tour',
    type: EventType.SIGHTSEEING,
    location: 'Cambridge, MA',
    description: 'Lunch: Sheng Jian Bao + Chi Cha San Chen. Dinner: Lobster Roll.',
  },
  // --- 12/28 ---
  {
    id: 'e6',
    date: '2025-12-28',
    time: '10:00',
    title: 'Freedom Trail',
    type: EventType.SIGHTSEEING,
    location: 'Boston Common',
    description: 'Lunch: Giacomos. Afternoon: Shopping at Newbury St.',
  },
  // --- 12/29 ---
  {
    id: 'e7',
    date: '2025-12-29',
    time: '10:00',
    title: 'Fenway Park',
    type: EventType.SIGHTSEEING,
    location: 'Fenway Park',
    description: 'Famous Red Sox stadium.',
  },
  {
    id: 'e8',
    date: '2025-12-29',
    time: '16:17',
    title: 'Amtrak to NY',
    type: EventType.TRANSPORT,
    location: 'BOS South Station',
    description: 'Arrive Penn Station @ 20:00.',
  },
  // --- 12/30 ---
  {
    id: 'e9',
    date: '2025-12-30',
    time: '10:00',
    title: 'The Met Museum',
    type: EventType.SIGHTSEEING,
    location: '1000 5th Ave',
    description: 'Directly to Egypt wing (Temple of Dendur).',
  },
  {
    id: 'e10',
    date: '2025-12-30',
    time: '14:00',
    title: 'Central Park South',
    type: EventType.SIGHTSEEING,
    location: 'Wollman Rink',
    description: 'Walk towards Columbus Circle winter market.',
  },
  {
    id: 'e11',
    date: '2025-12-30',
    time: '18:00',
    title: 'Times Square & Comics',
    type: EventType.SHOPPING,
    location: 'Times Square',
    description: 'Midtown Comics. Dinner: Los Tacos No.1.',
  },
  // --- 12/31 ---
  {
    id: 'e12',
    date: '2025-12-31',
    time: '10:00',
    title: 'Circle Line Cruise',
    type: EventType.SIGHTSEEING,
    location: 'Pier 83',
    description: '$68 ticket. Walk 25 mins.',
  },
  {
    id: 'e13',
    date: '2025-12-31',
    time: '13:00',
    title: 'Hudson Yards',
    type: EventType.SIGHTSEEING,
    location: 'The Vessel / Edge',
    description: 'High Line walk. Lunch: Lobster roll / Tacos @ Chelsea Market.',
  },
  {
    id: 'e14',
    date: '2025-12-31',
    time: '16:00',
    title: 'West Village',
    type: EventType.SIGHTSEEING,
    location: 'Washington Sq Park',
    description: 'NYU Campus area.',
  },
  {
    id: 'e15',
    date: '2025-12-31',
    time: '18:30',
    title: 'Broadway Show',
    type: EventType.SIGHTSEEING,
    location: 'Broadway',
    description: 'Dinner: La Pecora Bianca. Arrive 45 mins early.',
  },
  // --- 01/01 ---
  {
    id: 'e16',
    date: '2026-01-01',
    time: '11:00',
    title: 'Bryant Park Market',
    type: EventType.SIGHTSEEING,
    location: 'Bryant Park',
    description: 'The Lodge for rest.',
  },
  {
    id: 'e17',
    date: '2026-01-01',
    time: '14:00',
    title: '5th Ave & Rockefeller',
    type: EventType.SHOPPING,
    location: 'Rockefeller Center',
    description: 'Xmas Windows, FAO Schwarz (Jellycat).',
  },
  {
    id: 'e18',
    date: '2026-01-01',
    time: '15:20',
    title: 'Top of the Rock',
    type: EventType.SIGHTSEEING,
    location: 'Rockefeller Center',
    description: 'Sunset & Night view. ($68*2)',
  },
  // --- 01/02 ---
  {
    id: 'e19',
    date: '2026-01-02',
    time: '11:00',
    title: 'Yankee Stadium Tour',
    type: EventType.SIGHTSEEING,
    location: 'Bronx (D train)',
    description: 'Ticket $70.05. 161 St Station.',
  },
  {
    id: 'e20',
    date: '2026-01-02',
    time: '13:00',
    title: 'Wall Street',
    type: EventType.SIGHTSEEING,
    location: 'Financial District',
    description: 'Charging Bull, 911 Memorial.',
  },
  {
    id: 'e21',
    date: '2026-01-02',
    time: '16:00',
    title: 'Grand Central & Morgan Lib',
    type: EventType.SIGHTSEEING,
    location: 'Midtown',
    description: 'J.P. Morgan Library Free Fri 5-7pm (Reserve!).',
  },
  // --- 01/03 ---
  {
    id: 'e22',
    date: '2026-01-03',
    time: '09:30',
    title: 'Williamsburg',
    type: EventType.SIGHTSEEING,
    location: 'Brooklyn',
    description: 'Breakfast: Radio Bakery. Vintage shopping.',
  },
  {
    id: 'e23',
    date: '2026-01-03',
    time: '13:30',
    title: 'Dumbo & Ferry',
    type: EventType.TRANSPORT,
    location: 'Dumbo',
    description: 'Ferry ($4) - sit on right side for view.',
  },
  {
    id: 'e24',
    date: '2026-01-03',
    time: '16:30',
    title: 'Pier 35 Swings',
    type: EventType.SIGHTSEEING,
    location: 'Pier 35',
    description: 'Dinner: Mitr Thai.',
  },
  // --- 01/04 ---
  {
    id: 'e25',
    date: '2026-01-04',
    time: '10:00',
    title: 'SoHo Shopping',
    type: EventType.SHOPPING,
    location: 'SoHo (A/E train)',
    description: 'Cast iron buildings.',
  },
  {
    id: 'e26',
    date: '2026-01-04',
    time: '13:30',
    title: 'Central Park (Mid)',
    type: EventType.SIGHTSEEING,
    location: 'The Mall / Bow Bridge',
    description: 'Relaxing walk.',
  },
  // --- 01/05 ---
  {
    id: 'e27',
    date: '2026-01-05',
    time: '08:30',
    title: 'Woodbury Outlets',
    type: EventType.SHOPPING,
    location: 'Woodbury Common',
    description: 'Bus ticket $47.',
  },
  // --- 01/06 ---
  {
    id: 'e28',
    date: '2026-01-06',
    time: '08:00',
    title: 'Bryant Park Skating',
    type: EventType.SIGHTSEEING,
    location: 'Bryant Park',
    description: 'Early bird $25. No bags allowed.',
  },
  {
    id: 'e29',
    date: '2026-01-06',
    time: '11:30',
    title: 'Natural History Museum',
    type: EventType.SIGHTSEEING,
    location: 'AMNH',
    description: 'Blue Whale, T-Rex, Moai.',
  },
  // --- 01/07 ---
  {
    id: 'e30',
    date: '2026-01-07',
    time: '17:29',
    title: 'Flight UA434 EWR -> IAH',
    type: EventType.TRANSPORT,
    location: 'EWR',
    description: 'Flying time 04:17. To Houston.',
  },
  // --- 01/08 ---
  {
    id: 'e31',
    date: '2026-01-08',
    time: '10:00',
    title: 'NASA Space Center',
    type: EventType.SIGHTSEEING,
    location: 'Houston',
    description: 'Mission Control, Starship Gallery.',
  },
  // --- 01/09 ---
  {
    id: 'e32',
    date: '2026-01-09',
    time: '10:00',
    title: 'Natural Science Museum',
    type: EventType.SIGHTSEEING,
    location: 'Hermann Park',
    description: 'Butterfly Center, Paleontology.',
  },
  // --- 01/10 ---
  {
    id: 'e33',
    date: '2026-01-10',
    time: '11:00',
    title: 'The Galleria & Waterwall',
    type: EventType.SHOPPING,
    location: 'Houston',
    description: 'Large mall and waterfall park.',
  },
  // --- 01/11 ---
  {
    id: 'e34',
    date: '2026-01-11',
    time: '11:00',
    title: 'Sri Meenakshi & BBQ',
    type: EventType.FOOD,
    location: 'Pearland',
    description: 'Lunch: Killen\'s Barbecue.',
  },
  {
    id: 'e35',
    date: '2026-01-11',
    time: '18:33',
    title: 'Flight UA1341 IAH -> SFO',
    type: EventType.TRANSPORT,
    location: 'IAH',
    description: 'Home bound.',
  },
  {
    id: 'e36',
    date: '2026-01-11',
    time: '23:20',
    title: 'Flight UA853 SFO -> TPE',
    type: EventType.TRANSPORT,
    location: 'SFO',
    description: 'Arrive 1/13 05:45.',
  },
];

// Seeded Bookings Data
export const SEEDED_BOOKINGS: Booking[] = [
  // Flights
  {
    id: 'b1',
    type: 'FLIGHT',
    title: 'TPE to SFO',
    subTitle: 'United Airlines',
    date: '2025-12-26',
    time: '11:10',
    endTime: '06:40',
    location: 'TPE',
    endLocation: 'SFO',
    referenceCode: 'UA872',
    isSecure: false,
    details: { flightNumber: 'UA872' }
  },
  {
    id: 'b2',
    type: 'FLIGHT',
    title: 'SFO to EWR',
    subTitle: 'United Airlines',
    date: '2025-12-26',
    time: '08:30',
    location: 'SFO',
    endLocation: 'EWR',
    referenceCode: 'UA435',
    isSecure: false,
    details: { flightNumber: 'UA435' }
  },
  {
    id: 'b3',
    type: 'TRAIN',
    title: 'Amtrak BOS to NY',
    subTitle: 'Northeast Regional',
    date: '2025-12-29',
    time: '16:17',
    endTime: '20:00',
    location: 'BOS South Station',
    endLocation: 'NY Penn Station',
    referenceCode: 'AMT-882',
    isSecure: false,
  },
  {
    id: 'b4',
    type: 'FLIGHT',
    title: 'EWR to IAH',
    subTitle: 'United Airlines',
    date: '2026-01-07',
    time: '17:29',
    location: 'EWR',
    endLocation: 'IAH',
    referenceCode: 'UA434',
    isSecure: false,
    details: { flightNumber: 'UA434' }
  },
  {
    id: 'b5',
    type: 'FLIGHT',
    title: 'IAH to SFO',
    subTitle: 'United Airlines',
    date: '2026-01-11',
    time: '18:33',
    location: 'IAH',
    endLocation: 'SFO',
    referenceCode: 'UA1341',
    isSecure: false,
    details: { flightNumber: 'UA1341' }
  },
  {
    id: 'b6',
    type: 'FLIGHT',
    title: 'SFO to TPE',
    subTitle: 'United Airlines',
    date: '2026-01-11',
    time: '23:20',
    location: 'SFO',
    endLocation: 'TPE',
    referenceCode: 'UA853',
    isSecure: false,
    details: { flightNumber: 'UA853' }
  },
  // Accommodations
  {
    id: 'h1',
    type: 'HOTEL',
    title: 'Citizen M Boston Back Bay',
    date: '2025-12-26',
    endDate: '2025-12-29',
    time: '15:00',
    endTime: '11:00',
    location: '408 Newbury St, Boston, MA',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    referenceCode: 'BOS-CITIZEN',
    isSecure: false,
  },
  {
    id: 'h2',
    type: 'HOTEL',
    title: "Lun's Home (NYC)",
    date: '2025-12-30',
    endDate: '2026-01-07',
    location: '235 West 48th Street, NY',
    imageUrl: 'https://images.unsplash.com/photo-1496417263034-38ec4f0d6b21?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    referenceCode: 'FRIEND-STAY',
    isSecure: false,
    details: { roomType: 'Guest Room' }
  },
  {
    id: 'h3',
    type: 'HOTEL',
    title: "Aunt's Home (Houston)",
    date: '2026-01-07',
    endDate: '2026-01-11',
    location: '2605 Evergreen Dr, Pearland, TX',
    imageUrl: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    referenceCode: 'FAMILY-STAY',
    isSecure: false,
  },
];